### ISSUE TITLE
On SwapCrop

### ISSUE THREAD

**Issue by ddlee-cn** [assafshocher/InGAN#9]
Great work!
I wonder how the `SwapCrop` layer works in your code. Does it improve stability? What's the purpose to use it in the first place? Why disable it by default(the default value of `crop_swap_probability` is 0 in `conf`)?

**Comment by assafshocher** [comment]
Thanks for asking,
The SwapCrop was intended to allow image editing at test time, so that if the network is introduced with swapped crops but still required to generate an image with the same patch distribution then you will be able to swap crops at test time. We were able to demonstrate some nice results but that was unstable and damaged the quality of retargeting results when trained this way. We decided not to include this feature in the paper eventually. 
I guess that with some engineering this can be incorporated well.

**Comment by ddlee-cn** [comment]
I see. Thanks for your response.
